# Generated by Django 5.1.7 on 2025-03-15 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('egg_performance_avg', models.IntegerField()),
                ('weight_avg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('cell_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('AUTUMN', 'Autumn'), ('WINTER', 'Winter')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('passport', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('egg_performance_month', models.IntegerField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hens_app.breed')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hens_app.cell')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='diet_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hens_app.diet'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('f', 'full-time'), ('p', 'part-time')], max_length=10)),
                ('status', models.CharField(choices=[('a', 'active'), ('f', 'fired')], max_length=10)),
                ('salary', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hens_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hens_app.cell')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hens_app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hens_app.workshop'),
        ),
    ]
