# Generated by Django 4.2.19 on 2025-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
